baseURL = "http://example.org/"
title = "<xdf/>"
languageCode = "en-us"
theme = "coder"


[params]
  author = "XMPP Developers Foundation"
  info = "Building user-centric communication tools for the mass market"
  hideCredits = true
  hideCopyright = true

[[params.social]]
  name = "Github"
  weight = 1
  url = "https://github.com/XMPP-Developers-Foundation"

[[params.social]]
  name = "Discourse"
  weight = 2
  url = "https://discourse.xmpp-developers.foundation"

[[menu.main]]
  name = "Projects"
  url = "/projects/"
  weight = 1

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 2

